# Generated by Django 5.1.3 on 2026-01-10 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_word_unique_user_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word_per_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='native_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_language',
            field=models.CharField(default='Spanish', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='Spanish', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login_2fa', 'Login 2FA'), ('password_reset', 'Password Reset')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('user', 'text', 'language'), name='unique_word_per_user'),
        ),
    ]
