# Generated by Django 5.1.3 on 2026-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_remove_word_unique_word_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_goal',
            field=models.CharField(blank=True, default='Fluency', max_length=100),
        ),
    ]
